/**
 * Edge routing table: CMS path -> apps/public path. Only paths apps/public
 * really serves belong here; anything absent falls through to the CMS SPA.
 *
 * Free of Workers types so the CMS test runner can exercise it; worker/index.ts
 * is the only consumer.
 */

/** Served by apps/public under these same paths, so forwarded unrewritten. */
const PASSTHROUGH_PREFIXES = [
  '/_next/',
  // apps/public/public/* — pages reference these by absolute root path
  '/logo/',
  '/photos/',
  '/illustrations/',
  '/fonts/',
  '/api/'
];

/** Generated by app/robots.ts and app/sitemap.ts. */
const PASSTHROUGH_EXACT = ['/robots.txt', '/sitemap.xml'];

/**
 * apps/public's next-intl URL space, which its own NavBar links to. Matched as
 * a whole segment: the CMS routes /:organizationSlug here too, so /ptbr is not
 * a locale.
 */
const PASSTHROUGH_LOCALES = ['pt', 'en'];

export const isPublicPassthroughPath = (pathname: string): boolean =>
  PASSTHROUGH_PREFIXES.some(prefix => pathname.startsWith(prefix)) ||
  PASSTHROUGH_EXACT.includes(pathname) ||
  PASSTHROUGH_LOCALES.some(
    locale => pathname === `/${locale}` || pathname.startsWith(`/${locale}/`)
  );

/**
 * The locales apps/public actually serves (src/i18n/routing.ts there) —
 * anything else in the cookie is stale or tampered and would 404.
 */
const SUPPORTED_LOCALES = ['pt', 'en'];
const DEFAULT_LOCALE = 'pt';

/**
 * Reads the `NEXT_LOCALE` cookie next-intl's middleware sets on apps/public,
 * and the CMS's own i18n (Shared/translations/i18n.ts) also writes on an
 * explicit language change — the shared signal that syncs the language
 * across both apps. worker/index.ts passes the request's raw `Cookie` header
 * straight through, unparsed, so this is the one place that knows the name.
 */
export const resolveLocaleFromCookieHeader = (
  cookieHeader: string | null
): string => {
  const match = cookieHeader?.match(/(?:^|;\s*)NEXT_LOCALE=([^;]+)/);
  const value = match?.[1];

  return value && SUPPORTED_LOCALES.includes(value) ? value : DEFAULT_LOCALE;
};

/** null = matched the shape but declined; see the tournament root below. */
type Rewrite = [
  RegExp,
  (match: RegExpMatchArray, locale: string) => string | null
];

const SLUG = '([^/]+)';

/**
 * First segments that are never an organization slug. From the static routes
 * App.tsx declares ahead of /:organizationSlug/:tournamentSlug — the tournament
 * root below has no literal segment, so it would swallow /Organization/acme.
 */
const CMS_RESERVED_SEGMENTS = [
  'About',
  'Account',
  'AccountRecovery',
  'AccountReset',
  'Contact',
  'Faq',
  'Invite',
  'Organization',
  'Search',
  'SignIn',
  'SignUp',
  'TermsBR',
  'UseAsApp'
];

/** App.tsx declares these with a trailing `*`, matching any segment. */
const CMS_RESERVED_SEGMENT_PREFIXES = ['PrivacyPolicy', 'FacebookSignUp'];

const isReservedByCms = (segment: string): boolean =>
  CMS_RESERVED_SEGMENTS.includes(segment) ||
  CMS_RESERVED_SEGMENT_PREFIXES.some(prefix => segment.startsWith(prefix));

const ROUTES: Rewrite[] = [
  [/^\/$/, (_m, locale) => `/${locale}`],

  // lote 2 — institucional. Case sensitive, like App.tsx's <Route sensitive>.
  [/^\/About$/, (_m, locale) => `/${locale}/about`],
  [/^\/Faq$/, (_m, locale) => `/${locale}/faq`],
  [/^\/Contact$/, (_m, locale) => `/${locale}/contact`],
  [/^\/PrivacyPolicyBR$/, (_m, locale) => `/${locale}/privacy`],
  [/^\/TermsBR$/, (_m, locale) => `/${locale}/terms`],

  // Must precede the tournament root below: `Organization` is reserved there
  // (App.tsx:144) so that rule would otherwise decline and end the search.
  [
    new RegExp(`^/Organization/${SLUG}/?$`),
    (m, locale) => `/${locale}/${m[1]}`
  ],

  // lote 1 — rotas de leitura por torneio
  [
    new RegExp(`^/${SLUG}/${SLUG}/GameView/${SLUG}$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/jogos/${m[3]}`
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Player/${SLUG}$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/jogadores/${m[3]}`
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/PlayerStatsSummary$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/estatisticas/resumo`
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/PlayerStats$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/estatisticas`
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Teams/${SLUG}$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/times/${m[3]}`
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Phase/${SLUG}$`),
    (m, locale) => `/${locale}/${m[1]}/${m[2]}/fases/${m[3]}`
  ],

  // The tournament root, which renders its default phase. Last on purpose: no
  // literal segment of its own, so every rule above goes first.
  [
    new RegExp(`^/${SLUG}/${SLUG}/?$`),
    (m, locale) => (isReservedByCms(m[1]) ? null : `/${locale}/${m[1]}/${m[2]}`)
  ]
];

/**
 * `locale` should be whatever the CMS's own i18n resolved for this visitor
 * (Shared/translations/i18n.ts) — kept as a plain parameter, not read here,
 * so this module stays a pure function the CMS test runner can exercise
 * without a browser/Worker environment. worker/index.ts reads the NEXT_LOCALE
 * cookie and passes it in.
 */
export const resolvePublicPath = (
  pathname: string,
  locale: string = DEFAULT_LOCALE
): string | null => {
  for (const [pattern, toPath] of ROUTES) {
    const match = pathname.match(pattern);
    if (!match) continue;

    // A rule that declined ends the search: no later rule is more specific.
    return toPath(match, locale);
  }

  return null;
};
