/**
 * Edge routing table: CMS path -> apps/public path. Only paths apps/public
 * really serves belong here; anything absent falls through to the CMS SPA.
 *
 * Free of Workers types so the CMS test runner can exercise it; worker/index.ts
 * is the only consumer.
 */

/** Served by apps/public under these same paths, so forwarded unrewritten. */
const PASSTHROUGH_PREFIXES = [
  '/_next/',
  // apps/public/public/* — pages reference these by absolute root path
  '/logo/',
  '/photos/',
  '/illustrations/',
  '/fonts/',
  '/api/'
];

/** Generated by app/robots.ts and app/sitemap.ts. */
const PASSTHROUGH_EXACT = ['/robots.txt', '/sitemap.xml'];

/**
 * apps/public's next-intl URL space, which its own NavBar links to. Matched as
 * a whole segment: the CMS routes /:organizationSlug here too, so /ptbr is not
 * a locale.
 */
const PASSTHROUGH_LOCALES = ['pt', 'en'];

/**
 * apps/public's tournament sub-pages (app/[locale]/[org]/[tournament]/*),
 * already in their public Portuguese path shape. localePrefix: 'as-needed'
 * means the default locale (pt) reaches these with no /pt prefix, so they
 * can't be caught by PASSTHROUGH_LOCALES above — matched here instead. Never
 * collides with a CMS route: the CMS's own route names for these pages
 * (GameView, Player, PlayerStats, Teams, Phase) are English and capitalized.
 */
const PUBLIC_TOURNAMENT_SEGMENTS = [
  'jogos',
  'jogadores',
  'estatisticas',
  'times',
  'fases'
];
const PUBLIC_TOURNAMENT_SUBPAGE = new RegExp(
  `^/[^/]+/[^/]+/(?:${PUBLIC_TOURNAMENT_SEGMENTS.join('|')})(?:/.*)?$`
);

export const isPublicPassthroughPath = (pathname: string): boolean =>
  PASSTHROUGH_PREFIXES.some(prefix => pathname.startsWith(prefix)) ||
  PASSTHROUGH_EXACT.includes(pathname) ||
  PASSTHROUGH_LOCALES.some(
    locale => pathname === `/${locale}` || pathname.startsWith(`/${locale}/`)
  ) ||
  PUBLIC_TOURNAMENT_SUBPAGE.test(pathname);

// Locales apps/public actually serves (src/i18n/routing.ts there).
const SUPPORTED_LOCALES = ['pt', 'en'];
const DEFAULT_LOCALE = 'pt';

// NEXT_LOCALE: written by next-intl's middleware on apps/public and by the
// CMS's own i18n (Shared/translations/i18n.ts) — the shared sync signal.
export const resolveLocaleFromCookieHeader = (
  cookieHeader: string | null
): string => {
  const match = cookieHeader?.match(/(?:^|;\s*)NEXT_LOCALE=([^;]+)/);
  const value = match?.[1];

  return value && SUPPORTED_LOCALES.includes(value) ? value : DEFAULT_LOCALE;
};

/** null = matched the shape but declined; see the tournament root below. */
type Rewrite = [
  RegExp,
  (match: RegExpMatchArray, locale: string) => string | null
];

const SLUG = '([^/]+)';

// Same shape as commonValidators' mustBeSlug: lowercase alnum segments joined
// by single hyphens. Stricter than SLUG on purpose — the bare-org rule below
// has no literal segment of its own, so it must reject dotted filenames like
// favicon.ico or manifest.json and leave them on the CMS (env.ASSETS).
const ORG_SLUG = '([a-z0-9]+(?:-[a-z0-9]+)*)';

// apps/public's routing.ts sets localePrefix: 'as-needed' — the default
// locale (pt) never appears in the URL, and its middleware redirects any
// /pt/* path back to the bare path. Emitting /pt/* here would round-trip
// forever with that redirect, so the default locale is always omitted.
const withLocale = (locale: string, path: string): string =>
  locale === DEFAULT_LOCALE ? path : `/${locale}${path}`;

/**
 * First segments that are never an organization slug. From the static routes
 * App.tsx declares ahead of /:organizationSlug/:tournamentSlug — the tournament
 * root below has no literal segment, so it would swallow /Organization/acme.
 */
const CMS_RESERVED_SEGMENTS = [
  'About',
  'Account',
  'AccountRecovery',
  'AccountReset',
  'Contact',
  'Faq',
  'Invite',
  'Organization',
  'Search',
  'SignIn',
  'SignUp',
  'TermsBR',
  'UseAsApp'
];

/** App.tsx declares these with a trailing `*`, matching any segment. */
const CMS_RESERVED_SEGMENT_PREFIXES = ['PrivacyPolicy', 'FacebookSignUp'];

const isReservedByCms = (segment: string): boolean =>
  CMS_RESERVED_SEGMENTS.includes(segment) ||
  CMS_RESERVED_SEGMENT_PREFIXES.some(prefix => segment.startsWith(prefix));

const ROUTES: Rewrite[] = [
  [/^\/$/, (_m, locale) => (locale === DEFAULT_LOCALE ? '/' : `/${locale}`)],

  // lote 2 — institucional. Case sensitive, like App.tsx's <Route sensitive>.
  [/^\/About$/, (_m, locale) => withLocale(locale, '/about')],
  [/^\/Faq$/, (_m, locale) => withLocale(locale, '/faq')],
  [/^\/Contact$/, (_m, locale) => withLocale(locale, '/contact')],
  [/^\/PrivacyPolicyBR$/, (_m, locale) => withLocale(locale, '/privacy')],
  [/^\/TermsBR$/, (_m, locale) => withLocale(locale, '/terms')],

  // Must precede the tournament root below, or `Organization` (reserved
  // there) would decline and end the search before this rule ever runs.
  [
    new RegExp(`^/Organization/${SLUG}/?$`),
    (m, locale) => withLocale(locale, `/${m[1]}`)
  ],

  // lote 1 — rotas de leitura por torneio
  [
    new RegExp(`^/${SLUG}/${SLUG}/GameView/${SLUG}$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/jogos/${m[3]}`)
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Player/${SLUG}$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/jogadores/${m[3]}`)
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/PlayerStatsSummary$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/estatisticas/resumo`)
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/PlayerStats$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/estatisticas`)
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Teams/${SLUG}$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/times/${m[3]}`)
  ],
  [
    new RegExp(`^/${SLUG}/${SLUG}/Phase/${SLUG}$`),
    (m, locale) => withLocale(locale, `/${m[1]}/${m[2]}/fases/${m[3]}`)
  ],

  // The tournament root, which renders its default phase. Last on purpose: no
  // literal segment of its own, so every rule above goes first.
  [
    new RegExp(`^/${SLUG}/${SLUG}/?$`),
    (m, locale) =>
      isReservedByCms(m[1]) ? null : withLocale(locale, `/${m[1]}/${m[2]}`)
  ],

  // The bare organization page (App.tsx's /:organizationSlug -> OrganizationView),
  // its lowest-priority route: declared after every other route above, including
  // the tournament root. Same no-literal-segment situation, so it must also come
  // last and defer to CMS_RESERVED_SEGMENTS.
  [
    new RegExp(`^/${ORG_SLUG}/?$`),
    (m, locale) =>
      isReservedByCms(m[1]) ? null : withLocale(locale, `/${m[1]}`)
  ]
];

// `locale` is a plain parameter, not read here, so this stays a pure
// function the CMS test runner can exercise without a Worker environment —
// worker/index.ts resolves it from NEXT_LOCALE and passes it in.
export const resolvePublicPath = (
  pathname: string,
  locale: string = DEFAULT_LOCALE
): string | null => {
  for (const [pattern, toPath] of ROUTES) {
    const match = pathname.match(pattern);
    if (!match) continue;

    // A rule that declined ends the search: no later rule is more specific.
    return toPath(match, locale);
  }

  return null;
};
