language: node_js

env:
  - YARN_GPG=no

node_js:
  - "stable"

script:
  - yarn

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - yarn test

    - stage: deploy
      name: "Deploy"
      before_deploy:
        - yarn build
      deploy:
        dir: "build/"
        provider: netlify
        edge: true