describe('Phase Management', () => {
  beforeEach(() => {
    cy.visit('/SignIn')
    cy.get('body').should('be.visible')
    cy.get('input[name="username"]').type(Cypress.env('TEST_USERNAME'))
    cy.get('input[name="password"]').type(Cypress.env('TEST_PASSWORD'))
    cy.get('button[type=submit]').click()
    cy.get('body').should('be.visible')
    cy.xpath("//*[contains(text(), 'Gerencie seus campeonatos')]").click()
    cy.xpath("//*[contains(text(), 'Test Organization (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Test tournament (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Gerenciar')]").click()
    cy.xpath("//*[contains(text(), 'Fases')]").click()
  })

  it('Add new phase', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.wait(1000)
    cy.get('a[href="/test-organization-cannot-delete/test-tournament-cannot-delete/NewPhase"]').click()
    cy.wait(1000)
    cy.get('input[name="title"]').type('Test phase (can delete)')
    cy.wait(1000)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.reload()
    cy.xpath("//*[contains(text(), 'Test phase (can delete)') and contains(@class, 'title')]").should('be.visible')
  })

  it('Edit phase', () => {
    cy.xpath("//*[contains(text(), 'Test phase (can delete)')]").click()
    cy.wait(1000)
    cy.get('input[name="title"]').type(' edited')
    cy.wait(500)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.reload()
    cy.xpath("//*[contains(text(), 'Test phase (can delete) edited') and contains(@class, 'title')]").should('be.visible')
  })

  it('Delete phase', () => {
    cy.xpath("//*[contains(text(), 'Test phase (can delete) edited')]/../../div/button").dblclick()
    cy.wait(1000)
    cy.reload()
    cy.wait(1000)
    cy.xpath("//*[contains(text(), 'Test phase (can delete) edited') and contains(@class, 'title')]").should('not.exist')
  })
})