export const NODE_ENV = process.env.NODE_ENV;
export const REACT_APP_API_HOST = process.env.REACT_APP_API_HOST;
export const REACT_APP_AMPLITUDE_API_KEY =
  process.env.REACT_APP_AMPLITUDE_API_KEY;
export const REACT_APP_EMAILJS_PUBLIC_KEY =
  process.env.REACT_APP_EMAILJS_PUBLIC_KEY;
export const REACT_APP_EMAILJS_TEMPLATE_ID =
  process.env.REACT_APP_EMAILJS_TEMPLATE_ID;
export const REACT_APP_ENV = process.env.REACT_APP_ENV;
export const REACT_APP_BUILD_NUMBER = process.env.REACT_APP_BUILD_NUMBER;
export const REACT_APP_FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID;
export const REACT_APP_SCOREBOARD_APP_URL =
  process.env.REACT_APP_SCOREBOARD_APP_URL;
export const REACT_APP_RECAPTCHA_SITE_KEY =
  process.env.REACT_APP_RECAPTCHA_SITE_KEY;
