describe('Round Management', () => {
  beforeEach(() => {
    cy.visit('/SignIn')
    cy.get('body').should('be.visible')
    cy.get('input[name="username"]').type(Cypress.env('TEST_USERNAME'))
    cy.get('input[name="password"]').type(Cypress.env('TEST_PASSWORD'))
    cy.get('button[type=submit]').click()
    cy.get('body').should('be.visible')
    cy.xpath("//*[contains(text(), 'Gerencie seus campeonatos')]").click()
    cy.xpath("//*[contains(text(), 'Test Organization (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Test tournament (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Test draw phase (cannot delete)')]").click()
    cy.xpath("//a[contains(text(), 'Chaveamentos')]").click()
  })

  it('Add new draw', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Novo')]/../a").click()
    cy.wait(1000)
    cy.get('input[name="title"]').type('Test round (can delete)')
    cy.xpath("//*[contains(text(), 'Adicionar confronto')]").click()
    cy.wait(1000)
    cy.xpath("(//*[contains(@class, 'fa-history')])[1]").click()
    cy.xpath("(//*[contains(@class, 'fa-history')])[2]").click()
    cy.get('input[name="matches[0].firstTeamPlaceholder"]').type('First team placeholder')
    cy.get('input[name="matches[0].secondTeamPlaceholder"]').type('Second team placeholder')
    cy.wait(1000)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.xpath("//*[contains(text(), 'Test round (can delete)') and contains(@class, 'title')]").should('be.visible')
  })

  it('Edit draw', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Test round (can delete)')]").click()
    cy.wait(1000)
    cy.get('input[name="title"]').type(' edited')
    cy.wait(1000)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.xpath("//*[contains(text(), 'Test round (can delete) edited') and contains(@class, 'title')]").should('be.visible')
  })

  it('Delete draw', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Test round (can delete) edited')]/../../div/button").dblclick()
    cy.wait(1000)
    cy.xpath("//*[contains(text(), 'Test round (can delete) edited') and contains(@class, 'title')]").should('not.exist')
  })
})