describe('Game Tests', () => {
  beforeEach(() => {
    cy.visit('/SignIn')
    cy.get('body').should('be.visible')
    cy.get('input[name="username"]').type(Cypress.env('TEST_USERNAME'))
    cy.get('input[name="password"]').type(Cypress.env('TEST_PASSWORD'))
    cy.get('button[type=submit]').click()
    cy.get('body').should('be.visible')
    cy.xpath("//*[contains(text(), 'Gerencie seus campeonatos')]").click()
    cy.xpath("//*[contains(text(), 'Test Organization (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Test tournament (cannot delete)')]").click()
    cy.xpath("//*[contains(text(), 'Gerenciar')]").click()
    cy.xpath("//*[contains(text(), 'Partidas')]").click()
  })

  it('Add new game', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Novo')]/../a").click()
    cy.wait(1000)
    cy.xpath("//*[contains(text(), 'Equipe visitante')]/../div/div/div/div/div/div/div/div/input").type('Test team (cannot delete) A{enter}', {force: true})
    cy.xpath("//*[contains(text(), 'Equipe casa')]/../div/div/div/div/div/div/div/div/input").type('Test team (cannot delete) B{enter}', {force: true})
    cy.xpath("//*[contains(text(), 'Data | Hora')]/../div/div[1]/p/input").type('1')
    cy.get('.rdtDay').first().click()
    cy.get('input[name="info"]').click()
    cy.get('input[name="info"]').type('Test game (can delete)')
    cy.wait(1000)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.get('.card-header-title').should('contain.text', 'Test team (cannot delete) A')
  })

  it('Edit game', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Test team (cannot delete) A')]").click()
    cy.wait(1000)
    cy.get('input[name="info"]').type(' edited')
    cy.wait(1000)
    cy.get('button[type=submit]').click()
    cy.xpath("//*[contains(text(), 'Voltar')]").click()
    cy.wait(1000)
    cy.get('.card-header-title').should('contain.text', 'Test team (cannot delete) A')
  })

  it('Delete game', () => {
    cy.title().should('eq', 'Go Champs | Test tournament (cannot delete)')
    cy.xpath("//*[contains(text(), 'Test team (cannot delete) A')]/../../../../div/button").dblclick()
    cy.wait(1000)
    cy.get('.card-header-title').should('not.exist')
  })
})